## Data Preprocessing steps invovles

- getting dataset
- importing libraries
- importing datasets
- finding missing values
- encoding categorical data
- spiltting dataset into training and test set
- feature scaling

In [ ]:
# importing lib

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# reading csv file 

In [16]:
dataset = pd.read_csv('Data.csv')

In [ ]:
#display csv file 

In [17]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [19]:
# separate variables - input

In [23]:
x = dataset[['Country' , 'Age' , 'Salary']].values

In [24]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [26]:
y = dataset[['Purchased']].values

In [27]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [28]:
# finding missing values 


In [29]:
from sklearn.impute import SimpleImputer

In [32]:
imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean')

In [33]:
imputer = imputer.fit(x[:,1:3])

In [39]:
x[:,1:3] = imputer.transform(x[:,1:3])

In [40]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [41]:
# encoding categorical data

In [42]:
from sklearn.preprocessing import LabelEncoder

In [43]:
label_encoder_x = LabelEncoder()

In [44]:
x[:,0] = label_encoder_x.fit_transform(x[:,0])

In [45]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [46]:
# dummy encoding | to avoid co-relation 

In [47]:
from sklearn.preprocessing import OneHotEncoder

In [48]:
onehotencoder = OneHotEncoder()

In [52]:
x= onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

In [53]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [54]:
labelencoder_y = LabelEncoder()

In [55]:
y = labelencoder_y.fit_transform(y)

C:\Users\banda\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [56]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [59]:
# splitting the data

In [60]:
from sklearn.model_selection import train_test_split

In [61]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [62]:
x_train

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [63]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])

In [64]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [65]:
y_test

array([0, 0])

In [66]:
# feature scaling 

In [67]:
from sklearn.preprocessing import StandardScaler

In [68]:
sc_x = StandardScaler()

In [69]:
x_train = sc_x.fit_transform(x_train)

In [70]:
x_test = sc_x.fit_transform(x_test)

In [71]:
x_train

array([[-1.        ,  2.64575131, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667]])

In [72]:
x_test

array([[0., 0., 0.],
       [0., 0., 0.]])